name: flx
description: A Flutter Clean Architecture CLI tool
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  flx: bin/flx.dart
