name: flx_cli
description: A powerful Flutter Clean Architecture CLI tool for generating scalable project structures with GetX/BLoC state management, Freezed models, and comprehensive boilerplate code.
version: 1.0.2


repository: https://github.com/mdrakibulhaquesardar/flx_cli.git
documentation: https://flx-doc.netlify.app

topics:
  - flutter
  - cli
  - clean-architecture
  - code-generation
  - scaffolding

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  flx:
